In [32]:
import numpy as np
from scipy.io import loadmat  # this is the SciPy module that loads mat-files
import matplotlib.pyplot as plt
from datetime import datetime, date, time
from collections import OrderedDict
import pandas as pd
import numpy as np
import os

In [33]:
directory="result"
subjects_dict=OrderedDict()
for filename in os.listdir(directory):
    mat = loadmat(os.path.join(directory, filename))  # load mat-file
    subject_resps=np.concatenate( mat['resp'], axis=0 )
    subject_times=np.concatenate( mat['time'], axis=0 )
    subject_inds=np.concatenate( mat['ind'], axis=0 )
    data={'resp':subject_resps, 'time':subject_times, 'index':subject_inds}
    subject_df = pd.DataFrame(data=data)
    subject_df = subject_df.sort_values('index').reset_index(drop=True)
    subjects_dict[filename.split('.')[0][-1]]=subject_df

In [68]:
### Combine the test result of each testing subject into a joint array dataframe
joint_subjects_df = subjects_dict[subjects_dict.keys()[0]]
joint_resp_list=np.array(joint_subjects_df['resp'].tolist())
joint_resp_list=joint_resp_list.reshape(joint_resp_list.shape[0],-1)
joint_time_list=np.array(joint_subjects_df['time'].tolist())
joint_time_list=joint_time_list.reshape(joint_time_list.shape[0],-1)
for key, values in subjects_dict.items():
    ind_list=values['index'].tolist()
    if key != subjects_dict.keys()[0]:
        value_resp_list=np.array(values['resp'].tolist())
        value_resp_list=value_resp_list.reshape(value_resp_list.shape[0],-1)
        joint_resp_list=np.concatenate((joint_resp_list,value_resp_list), axis=1)
        value_time_list=np.array(values['time'].tolist())
        value_time_list=value_time_list.reshape(value_time_list.shape[0],-1)   
        joint_time_list=np.concatenate((joint_time_list,value_time_list), axis=1)

data={'resps':joint_resp_list.tolist(),'times':joint_time_list.tolist(),'index':ind_list}
joint_subject_df = pd.DataFrame(data=data)

joint_subject_df['mean_time']=np.mean(np.array(joint_subject_df['times'].tolist()),axis=1).tolist()
joint_subject_df.head(10)

,index,resps,times,mean_time
0,1,"[2, 2, 1]","[1.06008552364, 0.369689729307, 3.26728252296]",1.565686
1,2,"[2, 2, 2]","[1.20288574407, 0.315608600032, 0.810783573577]",0.776426
2,3,"[1, 2, 1]","[1.25283283397, 0.627966076892, 1.13117400455]",1.003991
3,4,"[1, 2, 1]","[0.876281629258, 0.251739192219, 1.83682358919]",0.988281
4,5,"[1, 2, 1]","[0.799558947125, 0.423851607737, 0.723735279589]",0.649049
5,6,"[1, 1, 1]","[0.802016332513, 0.698750997464, 1.77908441742]",1.093284
6,7,"[2, 2, 2]","[1.34795258436, 0.424314240448, 3.39597833948]",1.722748
7,8,"[2, 1, 1]","[0.700052293047, 0.522397664551, 1.20455136087]",0.809000
8,9,"[1, 2, 1]","[1.26295645782, 0.639789304651, 1.09719588863]",0.999981
9,10,"[2, 2, 2]","[0.67901447881, 0.453987262791, 0.724648556054]",0.619217